apiVersion: v1
data:
  admin-jwt-secret: vbYBU8G8m4CARk2Gvl6lig+zGYFrtlti6mMVTZGcJrCCydXIP7xsWqFdlB+LEfz/.j4r+yFEbQA1XcPjN.JKeaNvSsNvlFf3Kdc0SWEQ==
  app-host: jK2bmQX+rjFpPJ9TAcOdCNZ4jp96TV+kGGcwcJDqggTAmBY8699gDBvrm3IeS2pX.WGDetE10nr2Mramo.LQoISMbUcjDlEmPoixPRgg==
  database-host: cNue1r4A2nYo39qjoWSi2UPwz0P81Ds/q3Edh5wt16sTlo+iSC3gYR4F7Rqzwyqo.PWrCgkaCszFnXOlS.8CdpXWu3faXvfW00LC0yBw==
  postgresql-password: lFfG5PxaUUH1KY3mw3iJsrWlWuFJ/ToKKzrpZXEDNikVKo/+09iZPrVE997S/pCW.Is2EQT3HU76aUtZJ.Q/m45QbNa1OyqwaNDNekzQ==
kind: Secret
metadata:
  name: backend
type: Opaque
# kubesec:v:3
# kubesec:gcp:projects/eqx-host/locations/us-east1/keyRings/eqx/cryptoKeys/kubernetes-secrets:CiQAhvvwE0RdpJJQvuTG4lgz47cjGu/yCCIdhDcyNo8pFJcKVz4SSQAx+fAoEhy2K6MCVxHchR6RYg0wdJP9unSsLKcAF1vRDVnW0J1wC1nU9jKiAFytoE5Z4z9+IeV51Z5Vgc9BDVWbS4UYn2LgxvE=
# kubesec:mac:cp3Kv6ye3q31NwqV.KHVxhl1yJS0RGQt8Qpvzng==
