---
version: '3'
services:
    backend:
        image: strapi/strapi
        container_name: strapi
        restart: unless-stopped
        ports:
            - 1337:1337
        volumes:
            - ./backend:/srv/app
        environment:
            ADMIN_JWT_SECRET: W/6TMWPq3W4s1WJyn6QrrT4XneIGAsNvnqQkSxuktHwOLbbXowCRU6MxioUV6QgdlHUX09nTZWG9n2fcYZ4rpA==
            DATABASE_CLIENT: postgres
            DATABASE_NAME: eqx
            DATABASE_HOST: postgres
            DATABASE_PORT: 5432
            DATABASE_USERNAME: admin
            DATABASE_PASSWORD: admin
        depends_on:
            - postgres
        networks:
            - strapi-app


    frontend:
        build: frontend/
        ports:
            - 3000:3000
        volumes:
            - ./frontend:/usr/src/app
            - /usr/src/app/node_modules
        working_dir: /usr/src/app

    postgres:
        image: postgres
        environment:
            POSTGRES_DB: eqx
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
        volumes:
            - dataDB:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        networks:
            - strapi-app
volumes:
    dataDB:

networks:
    strapi-app:
