---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        deployment: frontend
    spec:
      containers:
      - name: frontend
        image: gcr.io/eqx-host/frontend
        ports:
        - containerPort: 3000
        env:
        - name: API_URL
          value: http://35.231.157.252
